# Generated by Django 5.0.6 on 2024-06-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='scope',
            field=models.CharField(default='basic', max_length=255),
            preserve_default=False,
        ),
    ]
