# Generated by Django 5.0.6 on 2024-06-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertoken_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='expires_in',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
